### ISSUE TITLE
Using this action with private repositories and registries

### ISSUE THREAD

**Issue by lerppana** [lukka/run-vcpkg#102]
Hi!

This issue might have nothing to do with this action itself, just my lack of understanding of how actions work. Maybe it is a request for new documentation or sample?

So my setup is that I have a repository called `vcpkg-registry`. I have configured a couple of vcpkg ports there, and in my main application project I have setup that registry to be used as a source for my shared library project. All of these repos are private. Now when I attempt to use my pipeline (that is pretty much copy paste the `hosted-basic` example) I of course get this error:

```
Fetching baseline information from https://github.com/lerppana/vcpkg-registry...
 Error: Couldn't find baseline "89f7510a4c0431b03a4012ec7011986b0b1dd150" for repo https://github.com/lerppana/vcpkg-registry:
  fatal: not a git repository: 'C:\Users\runneradmin\AppData\Local\vcpkg\registries\git\.git'

  Error: Failed to fetch https://github.com/lerppana/vcpkg-registry:
  Error: Failed to fetch ref 89f7510a4c0431b03a4012ec7011986b0b1dd150 from repository https://github.com/lerppana/vcpkg-registry.
  fatal: Cannot prompt because user interactivity has been disabled.
  bash: /dev/tty: No such device or address
  error: failed to execute prompt script (exit code 1)
  fatal: could not read Username for 'https://github.com': No such file or directory
```

So my question is if this action is able to use private repo registries? Is it just matter of configuring login credentials for git in runner, or is there some proper way to achieve this?

**Comment by lukka** [comment]
@lerppana please check out the [manual](https://github.com/lukka/run-vcpkg#user-manual), and let me know if the answer is not there, I am super happy to update it.

In the [flowchart](https://github.com/lukka/run-vcpkg#flowchart), the action is going to download the vcpkg's Git repo from a provided custom URL, and that may be a private repository. Is this the case where it is failing? Are you using a custom URL? A repro workflow with links to its content and its execution would help.

Please note that the output you shown above is not emitted by the `run-vcpkg` action. 

The only idea I have right now is that you could checkout the vcpkg repo using the [checkout](https://github.com/actions/checkout) action first, and then pointing `vcpkgDirectory` (and set `doNotUpdateVcpkg:true`) to the directory to prevent the action to try to fetch the repo content by downloading it, hence avoiding any auth issue. But first we should establish whether this is a auth issue :)

**Comment by lerppana** [comment]
Hi!

So my issue is when vcpkg starts installing, it will attempt to fetch the registry information from private repository, and cannot do that. 

This is what my `vcpkg-configuration.json` looks like:
```json
{
  "default-registry":
  {
    "kind": "git",
    "repository": "https://github.com/microsoft/vcpkg",
    "baseline": "7e94e6d35762949e6de72d9526807006ccc98b57"
  },
  "registries": [
    {
      "kind": "filesystem",
      "path": "vcpkg-registry",
      "packages": ["port1", "port2"]
    },
    {
      "kind": "git",
      "repository": "https://github.com/lerppana/vcpkg-registry",
      "packages": [ "port3" ],
      "baseline": "89f7510a4c0431b03a4012ec7011986b0b1dd150"
    }
  ]
}
```
I have some ports that I read from filesystem registry (folder in checked out repo). My goal is to move these ports into private git repo. Unfortunately I cannot read this repository because when I'm doing the installation phase, this happens:
```
 -- Running vcpkg install
  Fetching baseline information from https://github.com/microsoft/vcpkg...
  Fetching registry information from https://github.com/microsoft/vcpkg...
  Fetching baseline information from https://github.com/lerppana/vcpkg-registry...
  Error: Couldn't find baseline `"89f7510a4c0431b03a4012ec7011986b0b1dd150"` for repo https://github.com/lerppana/vcpkg-registry:
  fatal: path 'versions/baseline.json' exists on disk, but not in '89f7510a4c0431b03a4012ec7011986b0b1dd150'
  Error: Failed to fetch https://github.com/lerppana/vcpkg-registry:
  Error: Failed to fetch ref 89f7510a4c0431b03a4012ec7011986b0b1dd150 from repository https://github.com/lerppana/vcpkg-registry.
  fatal: Cannot prompt because user interactivity has been disabled.
  bash: /dev/tty: No such device or address
  error: failed to execute prompt script (exit code 1)
  fatal: could not read Username for 'https://github.com': No such file or directory
  -- Running vcpkg install - failed
```

I already tried to fix this by attempting to setup credentials with PAT like this before installation action, but it did not fix the issue:

```
      - uses: oleksiyrudenko/gha-git-credentials@v2.1
        with:
          global: true
          email: 'lassi@helynranta.com'
          actor: 'lerppana'
          token: ${{ secrets.PAT }}
```

of course this setup works fine at my laptop, it has never prompted my username or password.

**Comment by lukka** [comment]
@lerppana thanks for the explanation, it makes more sense to me now :) As you correctly noted, `vcpkg` is being run at the time `CMake` is being executed, and the spawn `vcpkg` fails at "auth time". I think and believe that there must be a way to make this working (similar as you tried already in your attempt), which I am not aware of.

Could you see if this helps? https://github.com/microsoft/vcpkg/issues/19467

If it works, I would be super happy to add a sample on how to leverage private vcpkg's registry. it would be a double win, as it would be both part of new user provided sample, and part of functional tests as well.

**Comment by lerppana** [comment]
Thanks @lukka for pointing those threads for me, it clarified the issue for me. I picked up two different methods that were discussed there which both worked fine:

```
#      method 1
      - run: echo "url=https://github.com"$'\n'"path=lerppana/vcpkg-registry"$'\n'"username=unused"$'\n'"password=${{ secrets.PAT }}"$'\n' | git credential approve
        shell: bash
        name: 'git credential approve'

#      method 2
      - run: git config --global credential.helper '!f() { echo username=unused; echo password=${{ secrets.PAT }}; }; f'
        shell: bash
        name: 'git credential helper setup'
```

both of them work with personal access tokens, I believe method 1 allows to set PAT per repo because path is given as parameter (which could be handy). It is bash script, but works fine with windows agent for me when `shell: bash` is specified. Otherwise it tries to default to pw.

**Comment by lerppana** [comment]
I created [this handle little action](https://github.com/lerppana/git-credential-approve/tree/v1) which makes the credential approve method a bit more expressive. usage is like this:
```
- uses: lerppana/git-credential-approve@v1
  with:
    personal-access-token: ${{ secrets.PAT }}
    path: 'lerppana/vcpkg-registry'
```

**Comment by lukka** [comment]
@lerppana awesome! In the future I'd like to create a sample showing vcpkg-registry working with private repos. 
Thanks for finding a working solution and refining it!
