### ISSUE TITLE
Caching doesn't work

### ISSUE THREAD

**Issue by Shatur** [lukka/run-vcpkg#108]
After switching to Manifest mode, caching stopped working. I am getting the following message in post log:

```
Can't add archive to itself::debug::File Size: 865632525
```

But I use exactly the same set of packages I used before (it worked with `v7`).
I use dependencies installation from CMake (e.g. `runVcpkgInstall` is set to `false`). To reduce the size I added `-D VCPKG_INSTALL_OPTIONS=--clean-after-build`, but the size is still big for the cache if I understand correctly.

[Here](https://github.com/crow-translate/crow-translate/runs/3944027656) is the run.
[Here](https://github.com/crow-translate/crow-translate/blob/master/.github/workflows/main.yml) is my configuration.
(I decided to use `vcpkgGitCommitId`)

Also not sure if it related, but I noticed that `vcpkg_installed` is located at `build/vcpkg_installed`. Is this expected? I thought that this folder should be in the root project folder.

**Comment by Shatur** [comment]
>  In the mean time, although it takes long time, it could help to enable verbose logging in the workflow and give a link to it, as its verbose log could reveal what the problem is.

Done, turned on and restarted the run. I'll ping you when it's ready :)

**Comment by Shatur** [comment]
Wait, I have a cache hit... How it possible? I clearly had cache error in the previous run...

**Comment by lukka** [comment]
@Shatur the bug about the identification of the vcpkg's Git commit id is fixed in `v10` branch. The warning/info message about "Can't add archive..." is still an outstanding problem? Let me know if you can run the workflow again (no changes needed on your side should be needed).

**Comment by Shatur** [comment]
It worked, now I have hit cache, thanks!
I can't see the message "Can't add archive ..." because of a cache hit. Maybe it was even with v7 and I just didn't notice, because the cache was working?
