### ISSUE TITLE
Setting to build debug/release-only libs set

### ISSUE THREAD

**Issue by kafeg** [lukka/run-vcpkg#117]
Hey! vcpkg has a feature to add to the triplets-files parameter: `set(VCPKG_BUILD_TYPE release)` or `set(VCPKG_BUILD_TYPE debug)`

So if it's possible to pass this param for `run-vcpkg` then it would be good to reduce build time for big ports like qt5-base and split debug/release workflows.

What do you think about inluding it to your project?

**Comment by kafeg** [comment]
Workaround for now is to forn vcpkg repo and set that value in fork and then use it as submodule.

**Comment by lukka** [comment]
@kafeg could you please elaborate more what the `run-vcpkg` action could be doing to reduce build time?
Is there anything that the workflow could be doing (e.g. setting up a env variable) that would achieve the same result?

**Comment by kafeg** [comment]
Unfortunately this is only one thing which i know and only by this way.

**Comment by lukka** [comment]
@kafeg storing everything under source control the triplet files with the desired `VCPKG_BUILD_TYPE` is definitively the best way to approach this problem. Supporting this from the `run-vcpkg` action would require modifying on the file the triplet file, which is not desirable, as it defeats the purpose of a reproducible build. 
I am closing this as i think the way to get this done is good as you described in this [comment](https://github.com/lukka/run-vcpkg/issues/117#issuecomment-990314887).
