### ISSUE TITLE
run-vcpkg should also hash vcpkg-configuration.json when computing hash key

### ISSUE THREAD

**Issue by equeim** [lukka/run-vcpkg#123]
vcpkg-configuration.json contains information about registries used by project and is located (if exists) next to the vcpkg.json.
It should also be used to compute cache key.

https://github.com/microsoft/vcpkg/blob/master/docs/users/registries.md

**Comment by lukka** [comment]
Fixed in #126 , please try `run-vcpkg@v10.1` and let me know!
