### ISSUE TITLE
there should be a way to avoid saving a partial/invalid cache of vcpkg binary artifacts 

### ISSUE THREAD

**Issue by lukka** [lukka/run-vcpkg#128]
run-vcpkg must implement the following:
- if the cache was correctly created, then it must be saved no matter what the workflow outcome is.
- if the cache was not correctly created, then the cache must not be saved, no matter what.

**Comment by Shatur** [comment]
@lukka Should it avoid caching at least when vcpkg step is failed? I have a workflow with saved cache and failed vcpkg step: https://github.com/crow-translate/crow-translate/runs/5240481054?check_suite_focus=true

**Comment by lukka** [comment]
@Shatur yes, when `run-vcpkg` fails, no cache should be saved. The fix is in `v10.1`, not in `v10`. Guess the original reason was that the `v10.1` is a breaking change (hence it should have been called v11 anyway), but whenever I can i need to sort this out and fix `v10` as well.

**Comment by Shatur** [comment]
> The fix is in v10.1, not in v10. 

Hm... I thought using `v10` applies the latest 10.x version.

**Comment by lukka** [comment]
@Shatur  thanks for confirming it! I knew the branches status was not correct after release of `v10.1`, but got distracted and forgot eventually about it.
Totally agreed that to streamline the action usage the fix in `v10.1` must be in `v10` as well.

**Comment by lukka** [comment]
FYI the only workaround is to leverage the `RUNVCPKG_NO_CACHE` environment variable. When it is set, the `run-vcpkg` post action is _not_ going to save the cache. For example, to avoid saving the cache when the workflow is failing, you can add a step that is setting the environment variable, such as:

```yaml

run: |
  echo "RUNVCPKG_NO_CACHE=1" >> $GITHUB_ENV
if: ${{ failure() }}
shell: bash
```

I"d be glad if anyone can contribute with:
- new ideas on how to solve the problem of storing incomplete/partial cache..
- other strategies to avoid saving incomplete cache.
- document other strategies.

**Comment by akrieger** [comment]
> you can add a step that is setting the environment variable, such as:
> 
> ```yaml
> run: |
>   echo "RUNVCPKG_NO_CACHE=1" >> $GITHUB_ENV
> if: ${{ failure() }}
> shell: bash
> ```

The check should be
```
if: ${{ failure() || cancelled() }}
```
because a cancellation doesn't count as a failure, but a job can be cancelled in the middle of a vcpkg dependency build.

**Comment by lukka** [comment]
FYI in this PR https://github.com/lukka/run-vcpkg/pull/161 documentation is added to let user properly handle cancellation/failure in their workflow in order to not store potentially broken cached data in the GitHub cache service.

**Comment by lukka** [comment]
as PR #161 has been completed, the documentation of how to avoid storing partial cache generated by vcpkg has been added, and this item could be closed.
Let me know if there is anything to do on `run-vcpkg` side in order to have a better solution for this one, thanks!
