### ISSUE TITLE
runVcpkgInstall installs in wrong directory

### ISSUE THREAD

**Issue by Shatur** [lukka/run-vcpkg#131]
I noticed that using `runVcpkgInstall` causes cache to unpacked twice.
Here is my workflow run: [log.txt](https://github.com/lukka/run-vcpkg/files/8107929/log.txt)
The disk is running out of space because packages are now installed twice, once during the run-vcpkg step and a second time on build.

I would expect a second run to see that the packages are already installed.

**Comment by lukka** [comment]
@Shatur I wonder if running `vcpkg install` twice is really required in your scenario. I'd just let it run once by the vcpkg's toolchain (i.e. when `CMake` is being run). If you decide to run `vcpkg install` by `run-vcpkg` (which happens by invoking directly vcpkg and you can customize it by setting the [`runVcpkgFormatString`](https://github.com/lukka/run-vcpkg/blob/main/action.yml#L50) input), differences in behavior are expected compared to the scenario where `vcpkg install` is run by the toolchain. See this conversation for example: https://github.com/microsoft/vcpkg/issues/19424#issuecomment-898024385

If i recall correctly, the vcpkg_installed directory is going to be put in the CMake build directory, and that is not known at the time of `run-vcpkg` (which happens before).  I believe that there may be a way to enforce it by driving appropriately env var and vcpkg/CMake flags.

**Comment by Shatur** [comment]
>  I'd just let it run once by the vcpkg's toolchain (i.e. when CMake is being run).

This approach have an issue with cache: #128. I thought using `runVcpkgInstall` option will allow me to avoid it by installing dependencies at run-vcpkg step. But the following makes total sense:

> If i recall correctly, the vcpkg_installed directory is going to be put in the CMake build directory, and that is not known at the time of run-vcpkg (which happens before).

So I will just wait for the cache fix.
