### ISSUE TITLE
vcpkgGitURL seems to have no effect

### ISSUE THREAD

**Issue by chrismile** [lukka/run-vcpkg#135]
Hi,

I have a vcpkg/GitHub actions test repository where I tried using vcpkgGitURL together with run-vcpkg, but I think that vcpkgGitURL might currently not work as expected.

In the logs, I get the following output:

```
Run lukka/run-vcpkg@v10.1
  with:
    vcpkgGitURL: https://github.com/zmughal/vcpkg.git
    vcpkgGitCommitId: af06f79f8d4e6dc5aca80c77565a729f54797f44
[...]
Running command '/usr/bin/git' with args 'clone,https://github.com/microsoft/vcpkg.git,-n,.' in current directory '/home/runner/work/ActionsTestRepo/ActionsTestRepo/vcpkg'.
```

It seems like run-vcpkg is able to pick up vcpkgGitURL, but still uses https://github.com/microsoft/vcpkg.git in the end. I would guess that this is probably a bug in run-vcpkg, right?

The action logs can be found here: https://github.com/chrismile/ActionsTestRepo/runs/5499515143?check_suite_focus=true

Thanks a lot for your support in advance!

**Comment by zmughal** [comment]
Would this just be a patch to <https://github.com/lukka/run-vcpkg/blob/refs/tags/v10.1/src/vcpkg-action.ts#L22>:

```diff
-export const vcpkgUrlInput = "VCPKGURLINPUT";
+export const vcpkgUrlInput = "VCPKGGITURL";
```

**Comment by chrismile** [comment]
> Would this just be a patch to https://github.com/lukka/run-vcpkg/blob/refs/tags/v10.1/src/vcpkg-action.ts#L22:
> 
> ```diff
> -export const vcpkgUrlInput = "VCPKGURLINPUT";
> +export const vcpkgUrlInput = "VCPKGGITURL";
> ```

Yes, I think that should work. I added a "vcpkgURLInput" field to my action in addition to "vcpkgGitURL", and while I now get the warning "Unexpected input(s) 'vcpkgURLInput'", it seems to use the correct URL.

It seems like "VCPKGURLINPUT" is also used by two files in the directory 'dist'. Are these files generated automatically or should the name also be replaced there?

**Comment by lukka** [comment]
Fixed in https://github.com/lukka/run-vcpkg/releases/tag/v10.2

**Comment by zmughal** [comment]
@chrismile, just a heads up, <https://github.com/microsoft/vcpkg/pull/23435> has been merged. I will delete the branch by tomorrow.

**Comment by chrismile** [comment]
> @chrismile, just a heads up, [microsoft/vcpkg#23435](https://github.com/microsoft/vcpkg/pull/23435) has been merged. I will delete the branch by tomorrow.

Sure, no worries, now that it is merged I can switch back to the upstream repo.
