### ISSUE TITLE
Running run-vcpkg in a clean shell environment

### ISSUE THREAD

**Issue by kmrashad** [lukka/run-vcpkg#141]
I have some packages installed on CI machine that will invalidate my binary cache.
Is it possible to run run-vcpkg in a clean environment. Locally, I can use `vpckg env` to have a clean shell. How can I achieve the same in the workflow. @lukka  Any ideas ?

**Comment by lukka** [comment]
@kmrashad could you elaborate the need of a "clean shell environment", and what the definition of the latter is?

**Comment by kmrashad** [comment]
@lukka using `--x-abi-tools-use-exact-versions` in CMakePresets.json solved issue. By clean environment, I mean use same tools such as 7zip, powershell, cmake etc.. Because vpckg uses them to compute hash and changing them invalidates existing binary caching of vcpkg. Closing this issue
