### ISSUE TITLE
How to exclude binaryCachePath directory from github action cache

### ISSUE THREAD

**Issue by kmrashad** [lukka/run-vcpkg#143]
How Can I exclude `VCPKG_DEFAULT_BINARY_CACHE` directory from saving to GH action cache ?
Right now I store bincache (2+GB) on a cloud server space and would like to avoid caching this in GH runner. 
Is there any arguments to exclude vcpkg/bincache directory ?

**Comment by lukka** [comment]
@kmrashad you may be wanting to use [doNotCache](https://github.com/lukka/run-vcpkg/blob/main/action.yml#L33)

**Comment by kmrashad** [comment]
Thanks @lukka
