### ISSUE TITLE
README.md lacks example for runVcpkgFormatString

### ISSUE THREAD

**Issue by jwillemsen** [lukka/run-vcpkg#147]
There is no example for runVcpkgFormatString, would be helpful for users, this looks to me a way to use this integration without a vcpkg.json file but specify which packages to install on the commandline (we did use `vcpkgArguments` before), see https://github.com/DOCGroup/ACE_TAO/blob/bd92596bbc63635a2ed2131322e6c659a5420586/.github/workflows/windows.yml#L127

**Comment by lukka** [comment]
@jwillemsen thanks for the information. Please note that in `run-vcpkg@v10` the usage of a `vcpkg.json` file is required, and you may need to rework your build process to upgrade from the previous version. The benefit is that you would be using the [vcpkg's manifest mode](https://github.com/microsoft/vcpkg/blob/master/docs/users/manifests.md).

The default value of the `unVcpkgFormatString` parameter is specified in [action.yml](https://github.com/lukka/run-vcpkg/blob/main/action.yml#L50), which could be used to customize how the command line leveraging the `vcpkg.json` file looks like. I would not suggest to try to install packages specified in that command line, as this way of working is intentionally not supported in `v10`.

You should be able to upgrade to latest version by using multiple values for [`vcpkgJsonGlob`](https://github.com/lukka/run-vcpkg/blob/main/action.yml#L39) which is the regexp used to locate `vcpkg.json`.

**Comment by jwillemsen** [comment]
Thanks for the feedback, working on a `vcpkg.json` and going to look into the manifest mode
