### ISSUE TITLE
Dependabot doesn't detect new vcpkg release

### ISSUE THREAD

**Issue by jwillemsen** [lukka/run-vcpkg#148]
FYI, dependabot doesn't detect the new v10 release, anyone on v7 has to upgrade manually, see https://support.github.com/ticket/personal/0/1691179

**Comment by lukka** [comment]
@jwillemsen I cant see the ticket. Is there anything that could be done on the run-vcpkg side to solve this issue?

**Comment by jwillemsen** [comment]
The latest response from the github team

Hello Johnny,

I heard from our engineers and the issue is that if the action's repo has branch names that match release tag names, we will prefer the branch over the tag, and effectively pin the version to the branch. We are working on a solution for this, but right now the best work around is to use a more specific version tag in the workflow IE v7.4 instead of v7 in this specific case.

Kind regards,
Laurel

**Comment by jwillemsen** [comment]
See https://github.com/dependabot/dependabot-core/issues/5017

**Comment by lukka** [comment]
@jwillemsen thanks for the heads up about this! I upvoted the issue, thanks for posting the link.

**Comment by jwillemsen** [comment]
This has been fixed, dependabot will create PR to upgrade from v7 to v10
