### ISSUE TITLE
Example for when not using cmake

### ISSUE THREAD

**Issue by jwillemsen** [lukka/run-vcpkg#150]
Trying to upgrade from run-vcpkg v7 to v10. We are not using cmake, so the documented approach doesn't work. I have already migrated our github action to create a `vcpkg.json` (see https://github.com/DOCGroup/ACE_TAO/pull/1888) but now I need to point some environment variables to the location of the installed header/libs. The original locations doesn't seem to work, an example from which we can borrow would help, for example what is the correct location for `XERCESC_INCDIR`

**Comment by lukka** [comment]
@jwillemsen i think that problem you are experiencing is that the you are not using CMake and hence not consuming the CMake toolchain file that vcpkg provides, which setups the paths for libraries and includes.

If you are using MSBuild, you need to run the [vcpkg integrate install](https://vcpkg.io/en/docs/users/buildsystems/msbuild-integration.html#integration-methods) before building. I suggest to run the integration in a `run:` step.

**Comment by jwillemsen** [comment]
I managed to get this working, the `vcpkg integrate install` doesn't seem something useful for us, see https://github.com/DOCGroup/ACE_TAO/pull/1888 for the changes I made to our github action to use v10
