### ISSUE TITLE
how to use it with static library

### ISSUE THREAD

**Issue by caizhe666** [lukka/run-vcpkg#151]

**Comment by lukka** [comment]
@caizhe666 i would suggest to read the [vcpkg documentation](https://vcpkg.io/en/index.html), or looking into existing vcpkg issues (e.g. https://github.com/microsoft/vcpkg/issues/5110).
On the other hand, if this is not a vcpkg issues, let me know if this action somehow prevents you to achieve successfully your scenario.

**Comment by caizhe666** [comment]
> @caizhe666 i would suggest to read the [vcpkg documentation](https://vcpkg.io/en/index.html), or looking into existing vcpkg issues (e.g. [microsoft/vcpkg#5110](https://github.com/microsoft/vcpkg/issues/5110)). On the other hand, if this is not a vcpkg issues, let me know if this action somehow prevents you to achieve successfully your scenario.

i have read these things,i want to use static library in github action,but i cant find any documentation.here is my github action output:
```
Running command '"D:\a\Locker\Locker\vcpkg\vcpkg.exe"' with args '^"install^",^"--recurse^",^"--clean-after-build^",^"--x-install-root^",^"D:/a/Locker/b/vcpkg_installed^",^"--triplet^",^"x64-windows^"' in current directory 'D:\a\Locker\Locker'.
```
it always be ```x64-windows```,but i want ```x64-windows-static```

**Comment by lukka** [comment]
@caizhe666 a solid understanding of what a vcpkg's triplet is and how it works is really needed. I'd suggest to read about it on the vcpkg documentation. 

Regarding the `run-vcpkg` action, the readme.md file mentions [why and how](https://github.com/lukka/run-vcpkg#quickstart-with-instructions) the user could drive the [default triplet by setting appropriately the `VCPKG_DEFAULT_TRIPLET` env var](https://github.com/lukka/run-vcpkg#flowchart).

A useful link to ramp up quickly on the topic is also this one from SO: https://stackoverflow.com/questions/60266710/how-to-use-vcpkg-packages-with-different-triplets
It provides a practical example usage which may be useful for your scenario.

**Comment by caizhe666** [comment]
thanks,i found the solution!
```
{
      "name": "boost",
      "platform": "windows & static"
}
```
