### ISSUE TITLE
Please add Ports Overlay

### ISSUE THREAD

**Issue by KangLin** [lukka/run-vcpkg#154]
See: https://github.com/microsoft/vcpkg/issues/25167?notification_referrer_id=NT_kwDOAIKvvbIzNzgzMjk5MzE2Ojg1NjQ2Njk#issuecomment-1219240007

I test environment VCPKG_OVERLAY_PORTS . but it is invalid here.

Can you add overlay input?

**Comment by lukka** [comment]
@KangLin I think you could contribute to the documentation by adding instructions on how to set up overlay with the `run-vcpkg` action.

Either using `VCPKG_OVERLAY_PORTS` environment variable, or by modifying the default value of the `runVcpkgFormatString` input you should be able to leverage the "ports overlay" feature.

**Comment by KangLin** [comment]
I am use v7. I don't find runVcpkgFormatString input. it is in v10.
I test environment VCPKG_OVERLAY_PORTS . but it is invalid here.
Please see: https://github.com/KangLin/RabbitRemoteControl/blob/develop/.github/workflows/msvc.yml

**Comment by lukka** [comment]
@KangLin I looked to the workflow called [msvc](https://github.com/KangLin/RabbitRemoteControl/actions/workflows/msvc.yml) and could not see what the exact problem is. Looks like the execution with `run-vcpkg`, along with the environment variable `VCPKG_OVERLAY_PORTS` set, worked fine.
Could you please elaborate about what's the observed behavior and what is  the expected one? 
A link to a relevant error would be helpful, thanks.

**Comment by KangLin** [comment]
vcpkg current openssl version is 3.x.x. but I want to use openssl 1.1.1n. so that I create port folder in my project https://github.com/KangLin/RabbitRemoteControl/tree/develop/vcpkg/ports/openssl .
run the github action. it is use vcpkg openssl 3.x.x .
I think to the environment variable VCPKG_OVERLAY_PORTS isn't used.

**Comment by KangLin** [comment]
I test in locale. it is not work. so that maybe is vcpkg problem.

**Comment by KangLin** [comment]
Use environment variable VCPKG_OVERLAY_PORTS is work. Thanks @lukka response.

**Comment by lukka** [comment]
@KangLin thanks to let us know! if you'd like to contribute to the documentation with an example leveraging the `VCPKG_OVERLAY_PORTS`? Or drop in here a link to the workflow which uses overlays and I can figure out how to document this, thanks!

**Comment by KangLin** [comment]
@lukka  I'd be happy to contribute. Please tell me how to do it?

Example: https://github.com/KangLin/RabbitRemoteControl/blob/master/.github/workflows/msvc.yml
openssl 1.1.1n port: https://github.com/KangLin/RabbitRemoteControl/tree/master/vcpkg/ports/
See: https://github.com/microsoft/vcpkg/issues/25167
