### ISSUE TITLE
Error on post action

### ISSUE THREAD

**Issue by vadi2** [lukka/run-vcpkg#16]
Hey this error came up - first time I see it, but I figure you'd like to know about it:

https://github.com/vadi2/Mudlet/runs/617833613

**Comment by lukka** [comment]
@vadi2 did you try to re-run the failing workflow? If the error persist must be a bug in the action/cache code (probably in the [upload code](https://github.com/lukka/run-vcpkg/blob/master/actions/cache/src/cacheHttpClient.ts)), otherwise it is a network related issue.

In any case i might pull a newer version of action/cache, there are chances a lot of other fixes have been applied recently.

**Comment by lukka** [comment]
@vadi2  if you re-run and the error is persistent, please enable [ACTIONS_STEP_DEBUG](https://github.com/actions/toolkit/blob/master/docs/action-debugging.md) as well, this would help understanding where in the code the error comes from. And run it again to get full log, thanks!

**Comment by vadi2** [comment]
Yeah it was just transient. It looks like it errors throwing the error. Want me to close the issue?

**Comment by lukka** [comment]
@vadi2 this issue is useful to remind me to pull next release of action/cache that might contain the fix of this transient problem (along others)

**Comment by lukka** [comment]
an update on this issue: the **cache** action did not have any new release until today, and the version used by **run-vcpkg** is still the most recent one, i.e. commit id "70655ec"

**Comment by dariosrbic** [comment]
@lukka there should be a big update to V2 of cache action coming in the next days which will enable cache on all trigger (currently only push and pull_request are allowed). Is there a possibility to test different cache versions (like master) without forking?

**Comment by lukka** [comment]
The actions/cache is stored as a _subrepo_ inside this repository, forking is the only way to instruct `run-vcpkg` to use a different `actions/cache` version.
This [PR](https://github.com/lukka/run-vcpkg/pull/19) is going to insert v1.2 of `actions/cache` from branch `release/v1`. 
I am going to insert any upcoming new version of `actions/cache` as well.

**Comment by lukka** [comment]
@vadi2 inserted [v1.2](https://github.com/actions/cache/releases/tag/v1.2.0) of actions/cache into run-vcpkg [v2](https://github.com/lukka/run-vcpkg/releases/tag/v2.2) branch (tag is `v2.2`). It should resolve the original issues experienced in this ticket.
