### ISSUE TITLE
Node 12 actions have been deprecated

### ISSUE THREAD

**Issue by quyykk** [lukka/run-vcpkg#163]
Node 12 actions have been deprecated by GitHub:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: lukka/get-cmake, lukka/run-vcpkg, lukka/run-cmake, lukka/run-vcpkg

Thanks again for these very useful actions!

**Comment by magnesj** [comment]
@lukka, can you please include this fix in the v7-branch? 
https://github.com/lukka/run-vcpkg/tree/v7

**Comment by lukka** [comment]
@magnesj could you please test the following branch with your workflow? e.g., `run-vcpkg@dev/v7_node16`

Question: do you get warnings regarding `save-state` deprecation as well?  I can see them validating the changes in https://github.com/lukka/run-vcpkg/pull/167

**Comment by magnesj** [comment]
> Question: do you get warnings regarding `save-state` deprecation as well? I can see them validating the changes in #167

Yes, we do get save-state warnings:
https://github.com/OPM/ResInsight/actions/runs/3295076025

**Comment by lukka** [comment]
@magnesj could you please check again? There should be no warnings as well.

**Comment by magnesj** [comment]
@lukka, sorry, I linked to the original run in my previous message. Everything works as expected, no warnings when running `run-vcpkg@dev/v7_node16` 
https://github.com/OPM/ResInsight/actions/runs/3310262368/jobs/5464270416

**Comment by lukka** [comment]
solved both on run-vcpkg@v10 and run-vcpkg@v7
