### ISSUE TITLE
save-state warning

### ISSUE THREAD

**Issue by jwillemsen** [lukka/run-vcpkg#168]
When using run-vcpkg@v10 we see this warning on the output

Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by lukka** [comment]
solved both on `run-vcpkg@v10` and `run-vcpkg@v7`
