### ISSUE TITLE
Defer completely to vcpkg to determine whether a cache is outdated

### ISSUE THREAD

**Issue by quyykk** [lukka/run-vcpkg#172]
Currently, run-vcpkg tries to detect when the cache needs to be recompiled. It does so by doing a couple of approximations: OS runner version, vcpkg.json hash and vcpkg/ version hash. This isn't perfect of course, and causes a lot of redundant cache misses that require building every dependency again. There's also the problem using overlay ports that aren't part of the hash and don't trigger rebuilds (when they're modified) at all.

It seems like we could defer to vcpkg completely instead (this assumes manifest mode):

- Restore binary cache, always (using a cache key without any restore keys of a simplified runner version: `win22`, `ubuntu22`, `macos12`, etc.).
- Ask vcpkg if any ports need to be rebuilt with the triplet specified as input to the action => if yes, at the end of the job we will upload the cache
- At the end ask vcpkg for a list of installed ports and check if it differs from the one in cache => if yes, a port was removed and we need to reupload the cache.
- When uploading the cache we ask vcpkg which ports were installed, and we only cache those (so that ports that have been removed aren't uploaded)

This basically guarantees a working build (through vcpkg's ABI detection) with as few rebuilds as possible I believe.

Thoughts? I would be willing to help out as much as I can (given my limited TS experience probably not a lot but :shrug:). Thanks!

**Comment by lukka** [comment]
@quyykk the algorithm you propose is sensible, and it needs support from the vcpkg tool itself, for example:
- how to ask vcpkg if anything needs to be rebuild.
- how to ask vcpkg for the list of the installed ports and computing the difference with the one in the cache.

I think that having vcpkg doing all the cache management work would be the perfect solution that would be also working and beneficial for any scenario (e.g., on the developer machine and on GH runners and so forth).

Probably as @rcoup suggested, one improvement we can make is having a way to answer the question "does the current binary cache directory need to be saved?", and that could be done by asking, somehow, to vcpkg whether any package was _not_ restored from the cache (the cache that has been restored by run-vcpkg before running vcpkg). In that case, `run-vcpkg` could be trying to replace the existing cache entry with the same key.

**Comment by rcoup** [comment]
@lukka the vcpkg team seem fairly responsive to GitHub issues, maybe open a discussion there and ask for a recommended approach or decide on the best changes to vcpkg to support this use-case?

**Comment by quyykk** [comment]
I asked around and it seems like everything already exists. The input needed is the requested feature and requested triplet.

If using the CMake toolchain (instead of calling `vcpkg install` manually), then CMAKE_BINARY_DIR is also required, but that can be read from the presets file.

> how to ask vcpkg if anything needs to be rebuild.

```bash
$ vcpkg install --dry-run --x-feature="" --triplet="" --x-manifest-root="." --x-install-root="CMAKE_BINARY_DIR/vcpkg_installed"
```
This is using the CMake toolchain. If someone is not using the CMake toolchain, but running `vcpkg install` manually, then the last two parameters are not needed. If the root (where `vcpkg.json` is) is somewhere else then the path needs to be adjusted for the manifest root argument.

It returns a list of ports that need to be built and removed.

-----

So I think it can work like this:

### Manifest mode

(either from CMake or using `vcpkg install`)

1. Run the command above to get the list of every port used
2. Restore everything from cache
3. Run the command again to see if there have been changes
4. [...] now the build is done using run-cmake
5. If there has been a change (see 3), then a new cache needs to be saved with the ports from 1)

### Manual mode (`vcpkg install`)

run-vcpkg needs to know about the ports that need to be installed, so they need to get passed to the action (no more executing `vcpkg install ...` in a separate step).

1. Restore everything from cache
2. Run `vcpkg install --dry-run --triplet="" [package list]` to get the list of changes (if any)
3. Install the packages with the same command but without `--dry-run`.
4. [...]
5. At the end if there was a change (see 2), then a new cache needs to be saved with the list of ports specified in the action input.

In both scenarios run-vcpkg could even save each port in a separate cache entry, to avoid unnecessary caches.

**Comment by quyykk** [comment]
Ah shoot, this might not work depending on what exactly run-vcpkg caches. Is only the local binary cache restored? (`~/.cache/vcpkg/archives/` on Linux)

**Comment by lukka** [comment]
@quyykk this is a detailed and actionable plan, thanks! `run-vcpkg` stores all the `VCPKG_ROOT` content along with the binary cache directory, so it is doable.

I wonder how the various solution compares:
 - current approach (cache key based on hash of vcpkg.json and vcpkg Git commit id): simple and effective.
 - this solution describe in detail above: quite complex, and more perfect than the previous one.
 - the solution suggested by the vcpkg team (last time I checked with them this is the suggested way): https://devblogs.microsoft.com/cppblog/vcpkg-accelerate-your-team-development-environment-with-binary-caching-and-manifests/

I think trying the last approach would be worth because it would be the simplest implementation and rely on vcpkg itself doing the cache job for us.

**Comment by quyykk** [comment]
> the solution suggested by the vcpkg team (last time I checked with them this is the suggested way): 

So for vcpkg itself to store/restore from the Actions cache itself? from what I can tell, but I'm not sure. That does indeed sound much better.

**Comment by lukka** [comment]
@quyykk sorry for the late answer! Yes, I mean that, and thanks a lot for  creating the PR onto the vcpkg-tool repository. I look forward to consume the new cache mechanism as soon as it get merged in.

**Comment by lukka** [comment]
@quyykk thanks a ton for adding GHA support to vcpkg! This issue should be solved with this release: 
https://github.com/lukka/run-vcpkg/releases/tag/v11.0

Let me know and thanks again!
