### ISSUE TITLE
v11 has been published onto the v10 branch

### ISSUE THREAD

**Issue by BurningEnlightenment** [lukka/run-vcpkg#194]
The breaking changes from v11 have been pushed to v10 (which is even two commits ahead of v11) as can be seen [here](https://github.com/lukka/run-vcpkg/network).

**Comment by lukka** [comment]
@BurningEnlightenment sorry for that and thanks a lot for reporting this! Should be fixed now, let me know!

**Comment by BurningEnlightenment** [comment]
Yes, the runners pull the correct version again.
