### ISSUE TITLE
run-vcpkg@v11 does not support prepended/appendedCacheKey

### ISSUE THREAD

**Issue by akrieger** [lukka/run-vcpkg#196]
We use prepended/appendedCacheKey for two main reasons:
- We have two different VS solutions in the repository, in two folders. One has a strict superset of packages compared to the other. We run two different CI jobs, one which builds both solutions and one which only builds the smaller. Using appendedCacheKey we create two different vcpkg 'bundles', bespoke for each build. If they share a cache key, without any other changes, the build with the smaller set of deps may 'win' and write the cache entry. The other build, being slower, will fail to write its dependencies to cache, and future hits will pull down the smaller package. This is unfortunate for us because the expanded set of deps include qt, which takes a very long time to bootstrap. Having the ability to generate two separate cache keys lets us avoid this issue and keep the cache bundle size for the faster job, smaller.
- Because we have multiple vcpkg.json, we get the output `Warning: The file vcpkg.json was found multiple times with glob expression '**/vcpkg.json'.` which historically meant _all_ of the vcpkg.json files were ignored for cache key calculations.
- We have custom triplet and port files in our repository. We used to use appendedCacheKey with the hashfiles feature to track changes to these files and automatically invalidate cache.

We would appreciate if support for these was reimplemented but understand that you likely dropped this support for a reason :)

**Comment by akrieger** [comment]
Not needed with the new builtin-to-vcpkg caching mechanism.

**Comment by lukka** [comment]
@akrieger sorry for the late, I was going to answer sooner or later. And you are right, the caching of built packages is delegated to `vcpkg` that is doing the perfect caching `run-vcpkg` could not be doing by itself. The good news is that the user manipulation of the cache's key is not necessary anymore.
