### ISSUE TITLE
One package not cached

### ISSUE THREAD

**Issue by wy-luke** [lukka/run-vcpkg#200]
I use `vcpkg` to compile `qt` in github actions.

I know it's not appropriate to do this, but I think that with caches only the first time would take long times.

But there is one package `qt5-declarative` not cache after I tried many times. And this package need 40 min almost to finish.....

I saw the all cache size is 10 GB and mine should have not exceed the limit.

After installed this package the log show below:

```
-- Performing post-build validation
Stored binaries in 0 destinations.
Elapsed time to handle qt5-declarative:x64-osx: 33 min
```

Thanks for help. Appreciate your work! Thanks.

**Comment by lukka** [comment]
@wy-luke is this happening when v`vcpkg` is running? In that case, likely it is a `vcpkg` issue and should be reported to https://github.com/microsoft/vcpkg/issues.
If you could provide a link to the workflow where `run-vcpkg` is being used, I can take a look at it.

**Comment by wy-luke** [comment]
@lukka https://github.com/CopyPlusPlus/CopyPlusPlus-Qt/actions/runs/4772412380/jobs/8514571273 
This is my action logs. Is this what you want?
I use your `run-vcpkg` firstly, then run `Configure Cmake`, in which `vcpkg` will install packages cause I'm using manifest mode.

When I run these locally, clear the `vcpkg` package folders then reconfigure cmake, all packages will be cached, including the `qt5-declarative`. It's fast. But in github actins the `qt5-declarative` always need to be compiled again.

Thank you so much.

**Comment by lukka** [comment]
@wy-luke thanks for the link to the log, that is helpful indeed. As you noted, vcpkg is somehow not storing the `qt5-declarative` port in the GitHub Action cache. I think this should be reported as a[ vcpkg's issue](https://github.com/microsoft/vcpkg/issues).

**Comment by wy-luke** [comment]
@lukka OK, I'll report it to there. Thanks for help.

**Comment by lukka** [comment]
@wy-luke would be helpful to have here a link/reference to the issue created on vcpkg, so that people can see how the problem is/will be solved. Do not hesitate to open a new issue here whenever you encounter one with `run-vcpkg`, thanks!

**Comment by wy-luke** [comment]
> @wy-luke would be helpful to have here a link/reference to the issue created on vcpkg, so that people can see how the problem is/will be solved. Do not hesitate to open a new issue here whenever you encounter one with `run-vcpkg`, thanks!

This is the issue created on vcpkg: https://github.com/microsoft/vcpkg/issues/31132
