### ISSUE TITLE
About Static Linking

### ISSUE THREAD

**Issue by onurkanbakirci** [lukka/run-vcpkg#201]
Is there any support to use `vcpkg` static linking feature? How to do by using `run-vcpkg?`?

**Comment by onurkanbakirci** [comment]
Okey. I found it. We can use `cmakeAppendedArgs` prop to make static linking. For example,
`cmakeAppendedArgs: "-GNinja -DKANGARU_TEST=ON -DVCPKG_TARGET_TRIPLET=x64-windows-static"`

**Comment by onurkanbakirci** [comment]
After digging into it, i think that instead of using cmakeAppendedArgs, using `vcpkgTriplet: x64-windows-static` is better.

**Comment by lukka** [comment]
@onurkanbakirci thank you for following up on this, I think that adding docs about this on the readme.md would be great.

**Comment by onurkanbakirci** [comment]
Hi @lukka , which section is suitable for that? Is `Quickstart with instructions` section on the `readme.md` file good?
