### ISSUE TITLE
Running the action in a container fails.

### ISSUE THREAD

**Issue by teo-tsirpanis** [lukka/run-vcpkg#206]
Minimal repro: https://github.com/teo-tsirpanis/run-vcpkg-test/actions/runs/5693609846

**Comment by lukka** [comment]
@teo-tsirpanis the problem looks like that the "Check whether vcpkg repository is up to date" is failing while because the command: `git submodule status /__w/run-vcpkg-test/run-vcpkg-test/vcpkg` is failing with:

```
fatal: detected dubious ownership in repository at '/__w/run-vcpkg-test/run-vcpkg-test'
  To add an exception for this directory, call:
  
  	git config --global --add safe.directory /__w/run-vcpkg-test/run-vcpkg-test`
```

As a workaround you may try to use `doNotUpdateVcpkg:true`.

**Comment by lukka** [comment]
@teo-tsirpanis did the workaround worked? Do you think there is any sensible logic to implement in `run-vcpkg` to avoid the error:  "fatal: detected dubious ownership in repository at '/__w/run-vcpkg-test/run-vcpkg-test'"? I am all hear to know about it, thank you.
