### ISSUE TITLE
default vcpkg install directory

### ISSUE THREAD

**Issue by a-zakir** [lukka/run-vcpkg#212]
Hello,
if `env.VCPKG_INSTALLED_DIR` is not set then the install command is: 
Running command D:\a\<REPO_NAME>/<REPO_NAME>\vcpkg\vcpkg.exe"' with args '^"install^",^"--recurse^",^"--clean-after-build^",^"--x-install-root^",^"D:/a/**<REPO_NAME>**/b/vcpkg_installed^",^"--triplet^",^"x64-windows^"
would not be easier  with --x-install-root = "D:/a/**<REPO_NAME>/<REPO_NAME>**/vcpkg_installed"  or alongside the `vcpkg.json` manifest file?
 same question for `binaryCachePath`.
OS : windows

thanks

**Comment by lukka** [comment]
@a-zakir I can imagine that the directory called `b` could be a problem, and I think I need you help: could you elaborate which improvements you are foreseeing? Thank you.

**Comment by a-zakir** [comment]
@lukka : 
Project_Root_dir : 
                      |_vcpkg/
                      |_vcpkg.json
                      |_vcpkg_installed/
                      |_vcpkg_cache/ (could be in vcpkg_installed/ ??)
See https://learn.microsoft.com/en-us/vcpkg/users/buildsystems/cmake-integration#vcpkg_installed_dir

**Comment by a-zakir** [comment]
I understand the problem is when run_vcpkg install packages before the CMake configure step (cmake_binary_dir not set yet). 
I think it's a vcpkg problem, telling cmake to look for dependencies in the right place

**Comment by lukka** [comment]
@a-zakir FYI in `run-vcpkg@v11.3` the directory used for vcpkg artifacts it has been moved under the `GITHUB_WORKSPACE`. 
If you have any problem with the default location, let me know.
