### ISSUE TITLE
Unnecessary double compilation when using VCPKG_DEFAULT_TRIPLET

### ISSUE THREAD

**Issue by justusranvier** [lukka/run-vcpkg#221]
In any case where VCPKG_DEFAULT_TRIPLET is set to a value other than the default triplet for the platform vcpkg will believe it is cross-compiling and start will compiling host dependencies for the platform default triplet which then frequently then needs to be compiled for the target triplet as well.

This is fine if you really are cross compiling but if you are using a windows runner to build x64-windows-static packages then you aren't cross compiling and all that unnecessary compilation of host dependencies for x64-windows is just a waste of minutes and artifact storage space.

The solution is to [pass the `--host-triplet` argument](https://github.com/microsoft/vcpkg/issues/29769#issuecomment-1438448180) to tell vcpkg you aren't cross-compiling but this action has no way to do so when run-vcpkg is run by itself.

If there was a second environment variable analogous to VCPKG_DEFAULT_TRIPLET which was passed as `--host-triplet` then anyone who is using a non-default triplet without cross compiling could set it to avoid unnecessary redundant compilation.

**Comment by lukka** [comment]
@justusranvier what is the desired UX from the point of view of users of `run-vcpkg` and `run-cmake`? i.e. what are the new steps the action should do? Any additional inputs? etc etc. If I get it right, the users need an easy way instruct the action to match the `target` and the `host` triplets.

Note that both actions could drive the environment variable `VCPKG_DEFAULT_HOST_TRIPLET` which is one of [the ways to set the desired host triplet](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/users/host-dependencies.md#specifying-the-host-triplet).

Please note that on the similar subject, there is this PR that needs to be merged, it fixes the default triplet for ARM based runners: https://github.com/lukka/run-vcpkg/pull/218 . Feedback is welcome on the PR itself. @lionkor FYI

**Comment by justusranvier** [comment]
In a situation of using run-vcpkg together with run-cmake together in manifest mode then the host triplet can be set using cmake variables so in that case nothing needs to change.

However if run-vcpkg is being run with `runVcpkgInstall: true` then it should be possible to pass `--host-triplet` otherwise the behavior may not be correct.

**Comment by justusranvier** [comment]
I did not realize that vcpkg itself already understands the `VCPKG_DEFAULT_HOST_TRIPLET` environment variable. I wish they had a single up to date document that listed all their command line arguments and environment variables.

**Comment by justusranvier** [comment]
I confirmed that setting VCPKG_DEFAULT_HOST_TRIPLET in the action yml file results in correct behavior.
