### ISSUE TITLE
vcpkg.json link dead

### ISSUE THREAD

**Issue by 0-wiz-0** [lukka/run-vcpkg#224]
The vcpkg.json link in the README is dead.
Clicking around the vcpkg repository I found [this](https://github.com/microsoft/vcpkg/blob/master/docs/users/manifests.md) which points to [vcpkg.json syntax](https://learn.microsoft.com/en-us/vcpkg/reference/vcpkg-json).

**Comment by lukka** [comment]
Fixed, thank you.
