### ISSUE TITLE
Update v7 to Node.js 20

### ISSUE THREAD

**Issue by magnesj** [lukka/run-vcpkg#226]
Hi, we are still using `v7`. We will appreciate if `v7 `branch is updated to latest Node.js 20 to avoid disruption of our build actions.

Thanks.

**Comment by lukka** [comment]
@magnesj yes, could you please try using and report back: `run-vcpkg@dev/node20-v7`.

**Comment by magnesj** [comment]
Thanks for the quick response, appreciate it.

The fix works as expected, now with no warnings.

https://github.com/OPM/ResInsight/actions/runs/8324185531

**Comment by lukka** [comment]
@magnesj thanks, I released a v7.6 from run-vcpkg@v7 : https://github.com/lukka/run-vcpkg/releases/tag/v7.6

**Comment by magnesj** [comment]
Thank you so much.
