### ISSUE TITLE
add ability to specify features when `runVcpkgInstall: 'true'`

### ISSUE THREAD

**Issue by ekoby** [lukka/run-vcpkg#236]
this would add `--x-feature` options to vcpkg command invocation

**Comment by lukka** [comment]
@ekoby it is already possible by modifying the runVcpkgFormatString parameter at https://github.com/lukka/run-vcpkg/blob/66b1ea8d89609e8adecfeb38797f4479f447a374/action.yml#L51
That is the default value, you can set it to your own value in your workflow.

**Comment by ekoby** [comment]
Yes, I found that. Still, it would be nice to be able to append to default instead of stomping on it (in case it ever changes)

**Comment by lukka** [comment]
@ekoby let me know if you succeeded in using custom arguments when running `vcpkg install`.

**Comment by ekoby** [comment]
Yes, thanks! that worked fine.

**Comment by lukka** [comment]
Closing as solved by using the suggestion at https://github.com/lukka/run-vcpkg/issues/236#issuecomment-2332150403
