### ISSUE TITLE
Cache Behaviour

### ISSUE THREAD

**Issue by spinicist** [lukka/run-vcpkg#24]
Hello,

This is a general question which might be helpful to write up in the README. What exactly determines:
1. When the cache can be stored?
2. When the cache can be used?

For my current workflow (https://github.com/spinicist/QUIT/actions), building vcpkg and dependencies takes >30 minutes, whereas building my project takes only 5. Hence caching is a real game-changer. I have observed the following:
1. The cache is only stored at the end of the run in the "post vcpkg" phase, if every phase was successful. This was very frustrating for my build, because for every typo in my .yml file I had to wait 30 minutes for the dependencies to build. Would it be possible to store the cache directly after finishing a successful vcpkg+dependencies build instead?
2. I kicked off a build with a tag, which will create a Release with my setup. I did this via (approximately) `git commit -m "A release build"; git tag a_tag; git push && git push origin a_tag`. This starts two builds almost simultaneously in Github Actions, one for the first push and one for the tag. The first build correctly picked up the cached vcpkg information, but the tag did not. Why did the tag build not pick up the cache?

Thanks again for providing these actions, they're very useful.

**Comment by lukka** [comment]
1. the cache is stored only on successful workflows. It could be possible to let the user control this behavior by changing `post-if: 'success()'` into an expression which includes a variable controlled indirectly by the user. This is something that needs to be explored since I see no actual examples for doing this.
2. can you provide the links of the workflow runs' logs, ideally with the [ACTION_STEPS_DEBUG](https://github.com/actions/toolkit/blob/master/docs/action-debugging.md) set to true ?

**Comment by spinicist** [comment]
1. If you have time to implement something like this I think it could be very useful.
2. The workflow is running now.

Previous build that stored a cache is here (didn't have ACTION_STEPS_DEBUG set to true): https://github.com/spinicist/QUIT/actions/runs/145378853
First build (no tag, finds the cache) is here: https://github.com/spinicist/QUIT/actions/runs/145949044
Second build (tag, does not find the cache) is here: https://github.com/spinicist/QUIT/runs/802718822?check_suite_focus=true

If you need the full logs then the 2nd build is going to take 30-40 minutes to finish.

**Comment by lukka** [comment]
1. agreed.
2. the only explanation I can think of is that those are two different workflows, and the cache is scoped per workflow. There is no single mention of this on the [documentation](https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows#matching-a-cache-key) though. In fact the cache keys computed by the [run-vcpkg](https://github.com/marketplace/actions/run-vcpkg) action, up to the URLs used by the called actions/cache APIs (i.e. the one at `##[debug]Resource Url:`) are identical in both workflows.

**Comment by PazerOP** [comment]
1. Couldn't you just merge the "post" action into the run-vcpkg action itself? I might be missing something, but I don't see why it has to be two separate steps.

**Comment by lukka** [comment]
@PazerOP that's right, the restore/save could be done in the same step (i.e. inside the `run-vcpkg` action, no need for the post-action for the saving of the cache). The post-action step stem from the original idea was to save the cache only when all the workflow was completed successfully.

**Comment by Shatur95** [comment]
I have a question about cache. The first time my build was [successful and cached](https://github.com/crow-translate/crow-translate/runs/1246981844?check_suite_focus=true). But after that, the setup [still took 2.5 hours](https://github.com/crow-translate/crow-translate/runs/1249514303?check_suite_focus=true). With the following output:

```
Restore vcpkg and its artifacts from cache
  Cache's key = 'localGitId=2106721475-args=-800282226-os=1553167195-appendedKey=42'.
  Running restore-cache
  Cache Size: ~973 MB (1020766370 B)
```

**Comment by lukka** [comment]
@Shatur95 you are right that the behavior is unexpected indeed, it is due to the fact that the `vcpkgCommitId` must not contain a tag (nor a branch). In your workflow i see a tag being used. Just replace the tag with its resolved commit id and then it will work properly.

The input is properly documented, but probably the action should just error out in case its value is not a commit id. 

I'd suggest opening an issue (and what about a PR, that is even better :D ) about improving the management of the `vcpkgCommitId` input.

**Comment by Shatur95** [comment]
Thanks for the explanation! Opened #47. I would like to send a PR, but I do not know TS :D

**Comment by lukka** [comment]
please verify `lukka/run-vcpkg@v5` suits your needs, thanks!

**Comment by vadi2** [comment]
This is a fantastic change :+1:

**Comment by magnesj** [comment]
Yeah, this is a game changer for using this action, thank you!

**Comment by lukka** [comment]
@spinicist closing this issue, let me know if `run-vcpkg@v5` satisfied this ask, thanks!

**Comment by spinicist** [comment]
Other projects are getting in the way of trying this - I will let you know when I finally get a chance but I'm sure it will be good!

**Comment by spinicist** [comment]
Hello - finally had a chance to try. Sadly it looks like it doesn't play well with Manifest mode? Since originally raising this I've swapped to manifest mode and it looks like all my dependencies are being rebuilt at the `configure`. Will continue discussion over on #53
