### ISSUE TITLE
Unable to restore cache

### ISSUE THREAD

**Issue by FranciscoPombal** [lukka/run-vcpkg#25]
I'm trying to cache/restore vcpkg artifacts with vcpkg installed to a path under the `C:\` drive.

The reason I'm not using the default workspace directory (under `D:\`) is because there is not enough free space available
for the installation of all packages, even if installing one package at a time and clearing buildtrees between installations,
instead of installing everything at once by using the response file directly.

While there is enough free space on the `C:\` drive to install all packages successfully and complete the jobs,
I can't get the cache to restore correctly in subsequent jobs that attempt to use it. The problem is reproducible.

The cache restoration fails with the following errors:

```
C:/qbt_tools/vcpkg/: Can't create '\\\\?\\C:\\qbt_tools\\vcpkg'
C:/qbt_tools/vcpkg/.artifactignore: Can't create '\\\\?\\C:\\qbt_tools\\vcpkg\\.artifactignore'
C:/qbt_tools/vcpkg/.git/: Can't create '\\\\?\\C:\\qbt_tools\\vcpkg\\.git'
C:/qbt_tools/vcpkg/.gitattributes: Can't create '\\\\?\\C:\\qbt_tools\\vcpkg\\.gitattributes'
C:/qbt_tools/vcpkg/.github/: Can't create '\\\\?\\C:\\qbt_tools\\vcpkg\\.github'
C:/qbt_tools/vcpkg/.gitignore: Can't create '\\\\?\\C:\\qbt_tools\\vcpkg\\.gitignore'
C:/qbt_tools/vcpkg/.vcpkg-root: Can't create '\\\\?\\C:\\qbt_tools\\vcpkg\\.vcpkg-root'
C:/qbt_tools/vcpkg/bootstrap-vcpkg.bat: Can't create '\\\\?\\C:\\qbt_tools\\vcpkg\\bootstrap-vcpkg.bat'
C:/qbt_tools/vcpkg/bootstrap-vcpkg.sh: Can't create '\\\\?\\C:\\qbt_tools\\vcpkg\\bootstrap-vcpkg.sh'
...
... (same for all other vcpkg files)
...
tar.exe: Error exit delayed from previous errors.
restoreCache() failed: 'Error: Tar failed with error: The process 'C:\windows\System32\tar.exe' failed with exit code 1'.
Cache miss.
```

Example of run that cached the artifacts successfully: https://github.com/FranciscoPombal/qBittorrent/actions/runs/146840965
Example of run that failed to restore them: https://github.com/FranciscoPombal/qBittorrent/runs/806709981

Is this happening because it's not possible to restore cache to the `C:\` drive? Is this a limitation of the underlying `cache` action?
Any help appreciated.

**Comment by lukka** [comment]
@FranciscoPombal you may check the following:
- permission issue? Can the runner identity write to C:\ ?
- problem seems the usage of the Windows provided tar. Seems like the BSD one could be better, download/install and put it first in the path on your runner. Please take a look at this issue: https://github.com/actions/cache/issues/125
- report this issue on the npm package that is being used for the caching operations: https://github.com/actions/toolkit/tree/master/packages/cache
- there are other problems similar but not identical to yours: https://github.com/actions/cache/issues/198

**Comment by FranciscoPombal** [comment]
> @FranciscoPombal you may check the following:
> 
>     * permission issue? Can the runner identity write to C:\ ?

In my workflow file, I set the `vcpkgDirectory` to `C:\qbt_tools\vcpkg`, and there is no problem with setting up vcpkg or installing packages there. So at least there are enough permissions for that. But perhaps (again, my initial suspicion) automated actions such these ones used for caching don't have permissions to write there...

>     * problem seems the usage of the Windows provided tar. Seems like the BSD one could be better, download/install and put it first in the path on your runner. Please take a look at this issue: [actions/cache#125](https://github.com/actions/cache/issues/125)

Apparently, Windows is already using `bsdtar`: https://techcommunity.microsoft.com/t5/containers/tar-and-curl-come-to-windows/ba-p/382409. I don't think there is anything I'm doing in my workflow that could pull in another tar as mentioned in that issue. So I don't really think tar is the problem here.

>     * report this issue on the npm package that is being used for the caching operations: https://github.com/actions/toolkit/tree/master/packages/cache
>
>     * there are other problems similar but not identical to yours: [actions/cache#198](https://github.com/actions/cache/issues/198)

I'll check it out :+1:

Let me know if you think of something else.

**Comment by lukka** [comment]
@FranciscoPombal 
About `BSD tar`, I meant `GNU tar`, sorry :). Honestly I have not read this all, but there is a potentially related report in here that may be helpful: https://github.com/actions/toolkit/issues/479

**Comment by FranciscoPombal** [comment]
@lukka 

> @FranciscoPombal
> About `BSD tar`, I meant `GNU tar`, sorry :). Honestly I have not read this all, but there is a potentially related report in here that may be helpful: [actions/toolkit#479](https://github.com/actions/toolkit/issues/479)

That report mentions `Can't unlink already-existing object`, which is not the error I'm getting. I'm restoring to an empty location. In fact, before restoring, `C:\qbt_tools\vcpkg` doesn't even exist. Do I need to create the directory prefix before restoring? Is that the problem?

Anyway, I'll try to add `C:\Program Files\Git\usr\bin\tar.exe` first in the PATH and see what happens.

**Comment by lukka** [comment]
@FranciscoPombal I think you are right, the directory `c:\qbt_tools` is not being created anywhere.
The @actions/cache npm package ensures the output directory existence in [here](https://github.com/actions/toolkit/blob/dcf5c88bb39db3ae877e35b6fc0fa572b80c6fb8/packages/cache/src/internal/tar.ts#L49)
but by looking to the command line issued in your workflow, it really created the wrong directory, i.e. `D:/a/qBittorrent/qBittorrent`

This is the command line in your workflow:
`C:\windows\System32\tar.exe -z -xf D:/a/_temp/88ebc98a-5d9d-4953-9047-d5d830f972c4/cache.tgz -P -C D:/a/qBittorrent/qBittorrent`

The function [getWorkingDirectory ](https://github.com/actions/toolkit/blob/dcf5c88bb39db3ae877e35b6fc0fa572b80c6fb8/packages/cache/src/internal/tar.ts#L40)seems the root cause here.

Also, the command for creating the cache was this:

`C:\windows\System32\tar.exe -z -cf cache.tgz -P -C D:/a/qBittorrent/qBittorrent --files-from manifest.txt`

Isnit this caching the completely wrong set of files? i.e. under D:/a/... instead of under C:

It is something to report on the @action/cache package's issues.

**Comment by FranciscoPombal** [comment]
> @FranciscoPombal I think you are right, the directory `c:\qbt_tools` is not being created anywhere.
> The @actions/cache npm package ensures the output directory existence in [here](https://github.com/actions/toolkit/blob/dcf5c88bb39db3ae877e35b6fc0fa572b80c6fb8/packages/cache/src/internal/tar.ts#L49)
> but by looking to the command line issued in your workflow, it really created the wrong directory, i.e. `D:/a/qBittorrent/qBittorrent`
>
> This is the command line in your workflow:
> `C:\windows\System32\tar.exe -z -xf D:/a/_temp/88ebc98a-5d9d-4953-9047-d5d830f972c4/cache.tgz -P -C D:/a/qBittorrent/qBittorrent`

The `-P` option means "Don't strip leading slashes from file names when creating archives.", and in this case, `-C` is at the end so it affects nothing (it is order-sensitive and only affects what comes after it).

> Also, the command for creating the cache was this:
> 
> `C:\windows\System32\tar.exe -z -cf cache.tgz -P -C D:/a/qBittorrent/qBittorrent --files-from manifest.txt`
> 
> Isnit this caching the completely wrong set of files? i.e. under D:/a/... instead of under C:

If you look at the errors during restoration, it looks like the correct files were cached. The `-C` option just means "change directory". The actual files are added from the argument `--files-from`. As long as `manifest.txt` contains the correct absolute paths to the files that I want to cache, all is good. This is apparently the case.

It's strange, both command lines look fine to me - the decompression should work because the absolute paths were stored, and indeed there is the attempt to restore the files to their correct paths.

**Comment by lukka** [comment]
@FranciscoPombal thanks for the explanation. Is there any other lead to progress the investigation on? If you were using a self-hosted runner, you could try running the command yourself and verify what is going with full control of it.

**Comment by FranciscoPombal** [comment]
@lukka 

> @FranciscoPombal thanks for the explanation. Is there any other lead to progress the investigation on?

Right now I'm waiting for feedback on https://github.com/actions/toolkit/issues/506. In the meantime, I'm trying to get it to work by creating `C:\qbt_tools` beforehand. I'll also try to add `C:\Program Files\Git\usr\bin` to PATH another time. I already tried that once, but the build failed with a rather cryptic `nmake fatal error u1077 'echo' return code '0x1'` (the results I find with Google about it don't seem of any relevance to my case). Not sure if the error is related to the PATH change or just spurious, so I have to try again. I suspect it might be related though; `C:\Program Files\Git\usr\bin` probably contains some executables that are now enjoying precedence they shouldn't be enjoying.

> If you were using a self-hosted runner, you could try running the command yourself and verify what is going with full control of it.

I'm not using a self-hosted runner.

**Comment by FranciscoPombal** [comment]
@lukka 

Good news: looks like the issue can be worked around simply by creating the path prefix in advance. So, for example, if using `vcpkgDirectory: C:\qbt_tools\vcpkg` in the vcpkg setup step, one would need to run something like `mkdir C:\qbt_tools` before the vcpkg setup step.

Make of this what you will, I'm not sure if the underlying problem resides in your action or in the upstream `cache` action.

Here is an example run where this workaround was used to get cache restoration working: https://github.com/FranciscoPombal/qBittorrent/actions/runs/148077320.

**Comment by lukka** [comment]
@FranciscoPombal cool, thanks for reporting. Looks sensible to me that `run-vcpkg` action ensures the cached paths are existing at least, this issue could be just tracking this work to be done on `run-vcpkg`.

**Comment by FranciscoPombal** [comment]
@lukka 

This should probably be another issue (possibly even for the upstream `cache` action), but it seems I'm sporadically getting this error when attempting to restore the cache:

```
Running restore-cache
##[warning]restoreCache() failed: 'Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close'.
Cache miss.
```

Most recently happened in this run (third matrix leg/variant): https://github.com/FranciscoPombal/qBittorrent/runs/809641734
