### ISSUE TITLE
Update samples because add_triplet_to_cachekey tag is deleted.

### ISSUE THREAD

**Issue by crupest** [lukka/run-vcpkg#31]
It seems `add_triplet_to_cachekey` tag has been deleted but the samples are still using it.
My workflow using that tag resulted in error.
So the samples should be updated, I think.

Best regards!

**Comment by lukka** [comment]
@crupest thanks for reporting this issue! Fixed in https://github.com/lukka/CppBuildTasks-Validation/pull/5
