### ISSUE TITLE
Option to not use cache

### ISSUE THREAD

**Issue by FranciscoPombal** [lukka/run-vcpkg#32]
Hi, is it possible to choose to not use cache at all, other than using a version <=1.4 ?

The use case for this is: there are multiple workflows for which I want to use this action, but only one of them where I actually want this action to cache artifacts so that its execution time remains low. Since there is not enough space to cache everything, if every other workflow is also caching, the one "critical" workflow will often have its cache overwritten by that of some other workflow.

Please let me know if there is actually an option available for this that I've overlooked.

**Comment by lukka** [comment]
@FranciscoPombal it definitively makes sense to add an option to disable completely caching if not desired.
At the moment, the only way to do this it's to have a fixed key "e.g. "nocache" and cache an empty directory.

**Comment by FranciscoPombal** [comment]
@lukka 

> At the moment, the only way to do this it's to have a fixed key "e.g. "nocache" and cache an empty directory.

Would setting `vcpkgArtifactIgnoreEntries` to just `**/*\n` achieve this?

**Comment by lukka** [comment]
@FranciscoPombal the `vcpkgArtifactIgnoreEntries` is not effective on GitHub, but only on Azure DevOps pipeline.
I think that as of today only caching an empty directory is a workaround the could be working.

**Comment by FranciscoPombal** [comment]
@lukka

> @FranciscoPombal the `vcpkgArtifactIgnoreEntries` is not effective on GitHub, but only on Azure DevOps pipeline.
> I think that as of today only caching an empty directory is a workaround the could be working.

Probably a dumb question, but how can I tell this action to cache an empty directory? Do I just `rm -r $VCPKG_ROOT/*` before the end of the workflow or is there a better way?

**Comment by lukka** [comment]
@FranciscoPombal yes, that is the only way. 
If you can validate some [changes](https://github.com/lukka/run-vcpkg/pull/33), I created a [PR](https://github.com/lukka/run-vcpkg/pull/33) for a new input called `doNotCache`. You may set  this to `true`, and try if it works in your workflows?
You can use it like this:
```
uses: lukka/run-vcpkg@dev/disable_cache
with:
  doNotCache: true
  [...]
```

**Comment by FranciscoPombal** [comment]
@lukka

Here is a workflow run with that change: https://github.com/FranciscoPombal/qBittorrent/runs/914168623

I had to cancel it because it was hanging due to a bug with MSYS setup that is currently affecting vcpkg, but your change seems to work fine:

> Caching is disabled (doNotCache=true)

**Comment by FranciscoPombal** [comment]
@lukka 

Ok, here is a workflow run that succeeded: https://github.com/FranciscoPombal/qBittorrent/actions/runs/184636989

I removed most useful steps for building the actual application so that no actual useful artifacts were produced, but left in the installation of a package via vcpkg that is not affected by the aforementioned MSYS issue.

This should be enough confirmation that your patch is working correctly.

**Comment by lukka** [comment]
@FranciscoPombal thanks for testing it! 
Work completed in https://github.com/lukka/run-vcpkg/pull/33
