### ISSUE TITLE
Add support for latest vcpkg release

### ISSUE THREAD

**Issue by jwillemsen** [lukka/run-vcpkg#35]
We are using vcpkg for some github actions for our CI builds. We currently build vcpkg from github, latest sources but that is tricky. We don't want to have the burder to manually update our github actions to a new release, would it be possible to have a latest release option, when that is set run-vcpkg could see what is the latest release from github (currently https://github.com/microsoft/vcpkg/releases/tag/2020.06) and build that? At the moment there is a new release it would be automatically used.

**Comment by MehdiChinoune** [comment]
for people asking for the latest, vcpkg has added the support for caching packages on local/cloud machines.
for GHA, this is the code:
```
      - name: Setup NuGet Credentials
        run: |
          & $(vcpkg fetch nuget | select -last 1) sources add `
          -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" `
          -storepasswordincleartext `
          -name "GitHub" `
          -username ${{ github.repository_owner }} `
          -password "${{ secrets.GITHUB_TOKEN }}"

      - name: vcpkg package restore
        run: |
          vcpkg install "your packages"
```

**Comment by lukka** [comment]
Please take a look to [run-vcpkg@v10](https://github.com/marketplace/actions/run-vcpkg) and see if suites your needs. Feel free to reopen this or a new ticket about any problem you may see.
