### ISSUE TITLE
cannot find bootstrap-vcpkg.bat

### ISSUE THREAD

**Issue by YkeSmit1** [lukka/run-vcpkg#48]
I try to use run-vcpkg but I am not able to make it work. I get the error
  '"D:\a\TOSR\TOSR\vcpkg\bootstrap-vcpkg.bat' is not recognized as an internal or external command,
  operable program or batch file.
Probably I am missing something really simple, but I cannot figure it out.
The double quote in the beginning is suspicious.  
This is my actions [file](https://github.com/YkeSmit1/TOSR/blob/master/.github/workflows/dotnet-core.yml)

**Comment by lukka** [comment]
@YkeSmit1 you need to ensure the `vcpkg` submodule is being downloaded as well, by passing appropriate input to the checkout action.

**Comment by YkeSmit1** [comment]
Yes that was the reason. Thanks a lot! You made my day 👍 
Maybe you can add this to the documentation. That you also need to add
   submodules: true  to the checkout command. 
I will close the issue right now
