### ISSUE TITLE
What is a 'response file'?

### ISSUE THREAD

**Issue by vadi2** [lukka/run-vcpkg#5]
This action heavily uses the term 'response file' yet vcpkg's official documentation and `--help` mentions nothing about it, so there's a disconnect for a new user here.

**Comment by lukka** [comment]
A 'response file' is a text file containing the arguments to run vcpkg with, used here to store under source control the list of installed ports/triplets.
It is cited in the `./vcpkg --help` output:
```
@response_file                  Specify a response file to provide additional parameters
```

**Comment by vadi2** [comment]
How can one generate it?

**Comment by lukka** [comment]
Here there is a [sample](https://github.com/lukka/CppBuildTasks/blob/add_shell_support/README.md#use-vcpkgs-response-file-as-parameter). It is human authored, it contains the list of the ports you want to install, optionally you can have a different triplet per package (e.g. `sqlite3:x64-windows`), and a default triplet.

**Comment by vadi2** [comment]
thanks!
