### ISSUE TITLE
Retries for "premature close" error during cache restoration

### ISSUE THREAD

**Issue by justusranvier** [lukka/run-vcpkg#50]
I've noticed these messages appearing in the logs on a non-infrequent basis:

` Warning: restoreCache() failed: 'Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close'.`
`Cache miss.`

Whenever this happens all my dependencies are rebuilt which for some projects can be expensive (~2 hours).

As far as I can tell this is a transient error caused by the vm being paused so it would be nice to have at least one retry for this error to avoid unnecessary dependency rebuilding.

**Comment by lukka** [comment]
@justusranvier could you please provide a link to a workflow execution that failed that way, with the [debug log enabled](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/enabling-debug-logging), thanks.

**Comment by lukka** [comment]
please verify `lukka/run-vcpkg@v5` suits your needs, thanks!

**Comment by justusranvier** [comment]
I've switched my scripts to v5 and I'll keep an eye on them. Since the timeouts were happening intermittently it can't conclusively say the problem is fixed but the initial results look good.

**Comment by lukka** [comment]
Feel free to report any problem you may experience!
