### ISSUE TITLE
Export location of downloaded Ninja executable

### ISSUE THREAD

**Issue by vadi2** [lukka/run-vcpkg#56]
Sometimes vcpkg ports fail, so it's convenient to work around issues by building with CMake yourself. Github Actions doesn't provide Ninja out of the box, but this action does - however the path is in `$env:VCPKG_ROOT\downloads\tools\ninja\1.10.1-windows` which is hardcoded to the version.

As a convenience for the unordinary cases, could the location of the ninja executable be standard or exported?

**Comment by lukka** [comment]
@vadi2 you could use [get-cmake](https://github.com/lukka/get-cmake) to install (and cache) latest `CMake` and `Ninja` on the `$PATH` and then launch it whenever needed. 
The one under the `$VCPKG_ROOT\downloads` is downloaded and used by the `vcpkg` tool.

**Comment by lukka** [comment]
Feel free to report any problem you may experience!
