### ISSUE TITLE
Confusing submodule / manifest instructions 

### ISSUE THREAD

**Issue by vadi2** [lukka/run-vcpkg#59]
> It is highly recommended to either use vcpkg as a submodule and to use vcpkg.json to declaratively specify the dependencies.

Does it mean `It is highly recommended to either use vcpkg as a submodule OR to use vcpkg.json to declaratively specify the dependencies.`, or `It is highly recommended to use vcpkg as a submodule and to use vcpkg.json to declaratively specify the dependencies.` ?

**Comment by lukka** [comment]
@vadi2 both of them should be used nowadays. 
The [vcpkg.json manifest file](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/manifests.md) is the best way to define the dependencies. 
The "response file" parameter which was what was suggested before the introduction of the manifest should be replaced with it. 

Note, you need a recent version of vcpkg that supports the vcpkg.json file, i.e. [[2020.11](https://github.com/microsoft/vcpkg/releases/tag/2020.11) or more recent.

**Comment by vadi2** [comment]
Alright, so perhaps `It is highly recommended to both use vcpkg as a submodule and to use vcpkg.json to declaratively specify the dependencies.` would be better?

**Comment by lukka** [comment]
Clarified the suggestions in latest `main` branch.
