### ISSUE TITLE
Github dark theme: flowchart difficult to follow

### ISSUE THREAD

**Issue by vadi2** [lukka/run-vcpkg#60]
Github has announced official dark theme support yesterday, and unfortunately the flowchart is not all that visible with it:

![Selection_515](https://user-images.githubusercontent.com/110988/101612514-02259200-3a0b-11eb-86ec-20ce82e3a109.png)

Perhaps the connector lines could be grey?

**Comment by lukka** [comment]
added a colored background, it is readable now.

Even better would be to export an `.svg` file from the `.dia` file, accepting PR for improving the diagrams!
