### ISSUE TITLE
Is a GitHub action really necessary to build a C++ based project?

### ISSUE THREAD

**Issue by lukka** [lukka/run-vcpkg#66]
Same ticket as [run-cmake/issues/41](https://github.com/lukka/run-cmake/issues/41), its content reported in here below:

## Introduction

In an ideal world, a mature ecosystem around the 30 years old C++ language would have standard and multi platform tools handling the dependency management, the building, the testing and so forth. Such as:

> cpp install && cpp build && cpp test

Ideally **those exact commands** would be run locally on the developer machine, or remotely on the build/test machines, in order to obtain **a perfectly reproducible software development process that can be run anywhere without any difference and no surprises**.
 
Reality is that (I can speak for [Azure DevOps](https://azure.microsoft.com/en-us/services/devops/) or [GitHub workflows](https://docs.github.com/en/free-pro-team@latest/actions/guides)) server side workflows require [Tasks](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/tasks?view=azure-devops&tabs=yaml) or [Actions](https://github.com/features/actions), which are essentially something the developer cannot run locally on the development machine.

In short, **the problem is the lack of 100% reproducible software development processes: the build/test process run by the developer on the local machine is not exactly identical to the one run on the server side workflow.**

## Let's create a reproducible  workflow, not polluted with code the developer cannot run!

In this [pure workflow](https://github.com/lukka/CppBuildTasks-Validation/blob/master/.github/workflows/hosted-pure-workflow.yml), it is presented how to create a workflow that is as close as possible to what the developer would run locally on the development machine.
The final intention is to give the developer the power to:
- having a reproducible workflow based on well known tools (i.e. CMake, Ninja, vcpkg).
- provide to the developer the knowledge to create a workflow without relying on any magic GitHub action.

The pure workflow is based on:
- absence of unneeded GitHub actions.
-  the fact that vcpkg can be bootstrapped (i.e .building the vcpkg executable) when the vcpkg's toolchain file is passed in at CMake's project file generation time.
-  the [vcpkg.json](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/manifests.md) manifest file that specifies declaratively the dependencies to be installed.

## Developers must own the knowledge and the choices

This information must be provided to the users in the `readme.md` files of [`run-vcpkg`](https://github.com/lukka/run-vcpkg) and [`run-cmake`](https://github.com/lukka/run-cmake): users must own the knowledge and take a conscious decision about whether any GitHub action is necessary.

**Comment by lukka** [comment]
Please note that discussion is best if kept on the original issue (as it is being updated from time to time), i.e. in here:
https://github.com/lukka/run-cmake/issues/41

**Comment by lukka** [comment]
Created a project template that documents how to use a _pure_ and a _non-pure_ workflow: https://github.com/lukka/CppCMakeVcpkgTemplate
This allows people to choose what fits their needs.

**Comment by vadi2** [comment]
That's great, thank you.
