### ISSUE TITLE
Github thinks action ran OK when it failed

### ISSUE THREAD

**Issue by vadi2** [lukka/run-vcpkg#72]
It looks like a transient error, but in the https://github.com/Mudlet/Mudlet/pull/4739/checks?check_run_id=1821768606 run the action failed - yet github thinks it was ok:

![image](https://user-images.githubusercontent.com/110988/106744866-9897bd80-6620-11eb-863e-11c4248c8622.png)

**Comment by lukka** [comment]
@vadi2 i spotted where the error is, thanks for the report!

**Comment by lukka** [comment]
@vadi2 fixed in `v6.3`

**Comment by vadi2** [comment]
Thanks man.
