### ISSUE TITLE
run-vcpkg cache

### ISSUE THREAD

**Issue by jmoguillansky-gpsw** [lukka/run-vcpkg#76]
Hi Lukka,
I've been using your github action successfully to build packages via vcpkg and cache them.
Today I tried building a different package via vcpkg and for some reason it's crashing.  

The package itself builds successfully but there seems to be a crash in run-vcpkg:

Please advise.

I'm using the following command:

- name: Restore from cache and install vcpkg
        uses: lukka/run-vcpkg@v6
        with:
          vcpkgGitCommitId: 595777db2332a3442b73f9af9f656355f207aec9
          vcpkgTriplet: x64-windows
          vcpkgArguments: shaderc
          cleanAfterBuild: false

Here's the log output

 -- Building x64-windows-rel
  -- Installing: ...
  -- Performing post-build validation
  -- Performing post-build validation done
  Stored binary cache: C:\Users\runneradmin\AppData\Local\vcpkg\archives\7f\7f0726ce6b0955530160c72a91edc69418d014b7.zip
  Building package spirv-tools[core]:x64-windows... done
  Installing package spirv-tools[core]:x64-windows...
  Installing package spirv-tools[core]:x64-windows... done
  Elapsed time for package spirv-tools:x64-windows: 18.47 min
  Starting package 4/4: shaderc:x64-windows
  Building package shaderc[core]:x64-windows...
  Error: Last command execution failed with error code '3221225477'.
:stopwatch: elapsed: 1458.747 seconds
Error: Last command execution failed with error code '3221225477'.
    at BaseUtilLib.throwIfErrorCode (D:\a\_actions\lukka\run-vcpkg\v6\dist\index.js:4930:19)
    at VcpkgRunner.<anonymous> (D:\a\_actions\lukka\run-vcpkg\v6\dist\index.js:5625:28)
    at Generator.next (<anonymous>)
    at fulfilled (D:\a\_actions\lukka\run-vcpkg\v6\dist\index.js:5440:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: run-vcpkg action execution failed: Error: Last command execution failed with error code '3221225477'.

**Comment by lukka** [comment]
@jmoguillansky-gpsw looks like some tool executed is failing with exit code `3221225477`. Do you have a link to the failed run?
Also, it may be needed to have a run where all the [output is verbosely collected](https://docs.github.com/en/actions/managing-workflow-runs/enabling-debug-logging) in the logs.

**Comment by jmoguillansky-gpsw** [comment]
Hi Lukka,
Here's a link to the run.  There's some extra code for debugging in the workflow file.
https://github.com/gopro/gopro-lib-node.gl/runs/1876803404?check_suite_focus=true

Thanks,
Jeff

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by lukka** [comment]
@jmoguillansky-gpsw the log shows that the command `vcpkg install --recurse shaderc --triplet x64-windows` is being executed, and during its execution it is failing and returning an exit code other than 0. Does not look like there is anything that we could possibly do on the `run-vcpkg` side in this case.

**Comment by lukka** [comment]
Let me know if there is otherwise anything that can be done on `run-vcpkg` side to address this problem
