### ISSUE TITLE
run-vcpkg down ? 

### ISSUE THREAD

**Issue by Milerius** [lukka/run-vcpkg#79]
It's seem i get the following error all the time now:

<img width="1062" alt="Capture d’écran 2021-02-28 à 16 41 18" src="https://user-images.githubusercontent.com/21139416/109424411-cb489200-79e3-11eb-9166-c082af35c3aa.png">

https://github.com/KomodoPlatform/atomicDEX-Desktop/runs/1998628847

**Comment by lukka** [comment]
@Milerius the problem is identical to #69, it is fixed in `run-vcpkg@v7`, please confirm. Note that all the cache are going to be regenerated by using `v7` since the key format changed.

**Comment by Milerius** [comment]
> @Milerius the problem is identical to #69, it is fixed in `run-vcpkg@v7`, please confirm. Note that all the cache are going to be regenerated by using `v7` since the key format changed.

Wow i missed lot of new stuff, now you support vcpkg manifest :O i may want to look at that as soon as possible.
