### ISSUE TITLE
Cache being always missing

### ISSUE THREAD

**Issue by otavio** [lukka/run-vcpkg#80]
I've been struggling to find why the cache is always being missed. 

```
Run lukka/run-vcpkg@v7
tool: C:\Program Files\Git\bin\git.exe
Fetching the Git commit id at 'D:\a\compress-tools-rs\compress-tools-rs\vcpkg' ...
0f0bd549dc2ac273bdb3dbd69b256815c09bcd0a
vcpkg identified at commitId='0f0bd549dc2ac273bdb3dbd69b256815c09bcd0a', adding it to the cache's key.
Cache's key = 'localGitId=707254936-args=1855044079-os=1553167250-imageVer=-2108626026-appendedKey=42-triplet=1258145250'.
Restore vcpkg and its artifacts from cache
⏱ elapsed: 20.593 seconds
Set output env vars
⏱ elapsed: 0.538 seconds
tool: C:\Program Files\Git\bin\git.exe
Fetching the Git commit id at 'D:\a\compress-tools-rs\compress-tools-rs\vcpkg' ...
ec6fe06e8da05a8157dc8581fa96b36b571c1bd5
Check whether vcpkg repository is up to date
  Checking whether vcpkg's repository is updated to commit id 'ec6fe06e8da05a8157dc8581fa96b36b571c1bd5' ...
  tool: C:\Program Files\Git\bin\git.exe
  error: pathspec 'D:\a\compress-tools-rs\compress-tools-rs\vcpkg' did not match any file(s) known to git
  Current commit id of vcpkg: 'ec6fe06e8da05a8157dc8581fa96b36b571c1bd5'.
  Is vcpkg repository updated? No
⏱ elapsed: 0.597 seconds
```

The workflow can be seen here: https://github.com/OSSystems/compress-tools-rs/blob/master/.github/workflows/windows.yml#L28-L33

**Comment by lukka** [comment]
After a quick look: is the vcpkg submodule cloned on disk by action/checkout?

**Comment by lukka** [comment]
My second look at it: the ` vcpkgGitCommitId: 2020.11-1` input is using a tag, which is not (yet) supported. Only explicit SHA-1 are accepted. This is a feature request tracked by https://github.com/lukka/run-vcpkg/issues/47

**Comment by otavio** [comment]
Ahh, thís explains it. I'll rework it and see if it helps.

**Comment by otavio** [comment]
Worked like a charm. It'd be nice if it could be mentioned on README as it would have saved me a bunch of time.

**Comment by lukka** [comment]
@otavio  Glad to know! Feel free to submit a PR to augment the `README.md`.

Note that the `README.md` never mentions the `vcpkgGitCommitId` indeed, mostly because if the recommendation of ["use vcpkg as a submodule"](https://github.com/lukka/run-vcpkg#best-practices) is followed then there is no need to set it at all :)

**Comment by otavio** [comment]
I am not a big fan of sub-modules as I think this is an external dependency and could be fetched during the build process.

Another nice feature of using it dynamically is if you ever need to test different versions of libraries, and in this case, this can be done using a matrix project.

**Comment by lukka** [comment]
Check for `vcpkgCommitId` being a SHA1 hash added in `run-vcpkg@v7.2`, and improved docs as well.
