### ISSUE TITLE
Action not correctly caching dependencies when using triplet-overlay 

### ISSUE THREAD

**Issue by sysnet-ai** [lukka/run-vcpkg#87]
I'm using run-vcpkg to build a library that I need to link statically to libprotobuf (but with DYNAMIC_CRT), so I need to use an overlay to get the right version.

This however seems to trip the caching. Even after consecutive successful runs the Windows job does a full rebuild of all the packages, while the Linux job (which doesn't use an overlay) is correctly retrieving them.

On the Post Restore from cache and install vcpkg step I'm seeing this:
```
Post job cleanup.
Save vcpkg and its artifacts to cache
  Cache hit occurred on the cache key 'localGitId=-574880384-args=42-os=1553167195-appendedKey=411780070-triplet=1258145250', saving cache is skipped.
```

Running VCPKG locally correctly detects the package, that's why I assume is something in the Action.

Thanks in advance for any pointers.

**Comment by lukka** [comment]
@sysnet-ai could you please provide a link to the workflow which is skipping (incorrectly) caching the binaries?

**Comment by sysnet-ai** [comment]
@lukka - I can't share the workflow since it is in a private repository, but I created a repo to reproduce it:
https://github.com/sysnet-ai/vcpkg_caching_test

As you can see 'Second Run' is not picking up anything from the cache even thou the first job does store something into the cache.

**Comment by lukka** [comment]
@sysnet-ai great to see a full repro of the problem, thanks!
I believe you could drop the `clients/cpp` from the input:
`additionalCachedPaths: ${{ github.workspace }}/clients/cpp/vcpkg_installed`
This is because the installation happens in `<repo-root>/vcpkg_installed` rather than `<repo-root>/cpp/clients/vcpkg_installed`.
Let me know if this helps, thanks!

**Comment by lukka** [comment]
@sysnet-ai also, please use the latest version, i.e., `lukka/run-vcpkg@v7`, and let me know as always, thanks!

**Comment by sysnet-ai** [comment]
@lukka - Thanks so much for the response

Nice catch with the `clients/cpp` path - however that is something we *do need* in the 'real' repo (It was there due to eager copy pasting) - could this be part of the issue?

On the repro repository: https://github.com/sysnet-ai/vcpkg_caching_test seems like the last update helped (Moving to v7 and removing the extra path).

I bumped to v7 and it seems like our main job is now running with correct caching.

Thanks again, closing this out.
