### ISSUE TITLE
Awkward to specify --overlay-ports

### ISSUE THREAD

**Issue by vadi2** [lukka/run-vcpkg#9]
I have to use a custom port of Lua 5.1 due to vcpkg's limitations (it doesn't support multiple versions of the same library very well) and it's a bit awakrd to specify the `--overlay-ports` argument. To my understanding my setup forces me to use `setupOnly` and then run a custom action to install what I need and provide the `--overlay-ports` flag.

Could there perhaps be an addition input to the action that allows you to specify the rest of the command line arguments to use?

**Comment by vadi2** [comment]
Nevermind - it looks like you can specify the argument as part of a response file as I tried initially, you just have to use `=` as the separator and not a space. This wasn't easy to spot at first.

**Comment by lukka** [comment]
@vadi2 you can also specify the arguments in the `vcpkgArguments` input, such as:

with:
    vcpkgArguments: '@responsefile.txt --overlay overlay'

If you put everything in the response file is fine as well, each overlay argument must be on the same line, such as i believe:

`--overlay-ports="..\experimental-ports\sqlite3"`
